# $schema: https://raw.githubusercontent.com/Axual/ksml/refs/tags/1.0.8/docs/ksml-language-spec.json

# aggregate Operation Test - generates test data for aggregate pipeline

streams:
  input_target:
    topic: test-input-aggregate
    keyType: avro:SimpleKey
    valueType: avro:SimpleValue

producers:
  aggregate_data_producer:
    to: input_target
    interval: 2s
    generator:
      globalCode: |
        global aggregateCounter
        aggregateCounter = 0
      code: |
        global aggregateCounter
        aggregateCounter += 1

        current = aggregateCounter

        key = None
        if current % 10 != 0:
          key = dict()
          key["count"] = current

        value = None
        if current % 10 != 1:
          value = dict()
          value["text"] = f"aggregate test data - {current}"
          value["count"] = current

      expression: (key,value)
      resultType: (avro:SimpleKey,avro:SimpleValue)
