include:
  - ../../test-compose.yml
# Run all services to get Red Panda
services:
  # Create test data
  prepare_cluster:
    image: apache/kafka:4.0.0
    hostname: kafka-setup
    depends_on:
      broker:
        condition: service_healthy
        restart: false
    restart: on-failure
    command: "bash -c 'echo Trying to create topics... && \
                         /opt/kafka/bin/kafka-topics.sh --create --if-not-exists --bootstrap-server broker:9093 --partitions 1 --replication-factor 1 --topic axual-testing-compat-test-join-stream-input && \
                         /opt/kafka/bin/kafka-topics.sh --create --if-not-exists --bootstrap-server broker:9093 --partitions 1 --replication-factor 1 --topic axual-testing-compat-test-join-table-j --config cleanup.policy=compact && \
                         /opt/kafka/bin/kafka-topics.sh --create --if-not-exists --bootstrap-server broker:9093 --partitions 1 --replication-factor 1 --topic axual-testing-compat-test-join-table-lj --config cleanup.policy=compact && \
                         /opt/kafka/bin/kafka-topics.sh --create --if-not-exists --bootstrap-server broker:9093 --partitions 1 --replication-factor 1 --topic axual-testing-compat-test-join-stream-input-oj && \
                         /opt/kafka/bin/kafka-topics.sh --create --if-not-exists --bootstrap-server broker:9093 --partitions 1 --replication-factor 1 --topic axual-testing-compat-test-join-stream-output-j && \
                         /opt/kafka/bin/kafka-topics.sh --create --if-not-exists --bootstrap-server broker:9093 --partitions 1 --replication-factor 1 --topic axual-testing-compat-test-join-stream-output-lj && \
                         /opt/kafka/bin/kafka-topics.sh --create --if-not-exists --bootstrap-server broker:9093 --partitions 1 --replication-factor 1 --topic axual-testing-compat-test-join-stream-output-oj && \
                         echo Done'"
