# $schema: https://raw.githubusercontent.com/Axual/ksml/refs/tags/1.0.8/docs/ksml-language-spec.json

# windowedAggregate Operation Test - generates test data for windowedAggregate pipeline

streams:
  input_target:
    topic: test-input-windowedAggregate
    keyType: avro:SimpleKey
    valueType: avro:SimpleValue

producers:
  windowedAggregate_data_producer:
    to: input_target
    interval: 2s
    generator:
      globalCode: |
        global windowedAggregateCounter
        windowedAggregateCounter = 0
      code: |
        global windowedAggregateCounter
        windowedAggregateCounter += 1

        current = windowedAggregateCounter

        key = None
        if current % 10 != 0:
          key = dict()
          key["count"] = current

        value = None
        if current % 10 != 1:
          value = dict()
          value["text"] = f"windowedAggregate test data - {current}"
          value["count"] = current

      expression: (key,value)
      resultType: (avro:SimpleKey,avro:SimpleValue)
