# $schema: https://raw.githubusercontent.com/Axual/ksml/refs/tags/1.0.8/docs/ksml-language-spec.json

# outerJoin Operation Test - generates test data for outerJoin pipeline

streams:
  input_target:
    topic: test-input-outerJoin
    keyType: avro:SimpleKey
    valueType: avro:SimpleValue

producers:
  outerJoin_data_producer:
    to: input_target
    interval: 2s
    generator:
      globalCode: |
        global outerJoinCounter
        outerJoinCounter = 0
      code: |
        global outerJoinCounter
        outerJoinCounter += 1

        current = outerJoinCounter

        key = None
        if current % 10 != 0:
          key = dict()
          key["count"] = current

        value = None
        if current % 10 != 1:
          value = dict()
          value["text"] = f"outerJoin test data - {current}"
          value["count"] = current

      expression: (key,value)
      resultType: (avro:SimpleKey,avro:SimpleValue)
