# $schema: https://raw.githubusercontent.com/Axual/ksml/refs/tags/1.0.8/docs/ksml-language-spec.json

# Count Operation Test - generates test data for reduce pipeline

streams:
  input_target:
    topic: test-reduce-stream-input
    keyType: avro:SimpleKey
    valueType: long

producers:
  reduce_data_producer:
    to: input_target
    interval: 1000
    generator:
      globalCode: |
        global reduceCounter
        reduceCounter = 0
      code: |
        global reduceCounter
        reduceCounter += 1

        current = reduceCounter

        key = dict()
        key["id"] = current%5

        value = None
        if current % 10 != 1:
          value = current

      expression: (key,value)
      resultType: (avro:SimpleKey,long)
