include:
  - ../../test-compose.yml
# Run all services to get Red Panda
services:
  # Create test data
  prepare_cluster:
    image: apache/kafka:4.0.0
    hostname: kafka-setup
    depends_on:
      broker:
        condition: service_healthy
        restart: false
    restart: on-failure
    command: "bash -c 'echo Trying to create topics... && \
                         /opt/kafka/bin/kafka-topics.sh --create --if-not-exists --bootstrap-server broker:9093 --partitions 1 --replication-factor 1 --topic axual-testing-compat-test-input-convert && \
                         /opt/kafka/bin/kafka-topics.sh --create --if-not-exists --bootstrap-server broker:9093 --partitions 1 --replication-factor 1 --topic axual-testing-compat-test-output-convert && \
                         /opt/kafka/bin/kafka-topics.sh --create --if-not-exists --bootstrap-server broker:9093 --partitions 1 --replication-factor 1 --topic axual-testing-compat-test-output-convert-k && \
                         /opt/kafka/bin/kafka-topics.sh --create --if-not-exists --bootstrap-server broker:9093 --partitions 1 --replication-factor 1 --topic axual-testing-compat-test-output-convert-v && \
                         echo Done'"
