# $schema: https://raw.githubusercontent.com/Axual/ksml/refs/tags/1.0.8/docs/ksml-language-spec.json

# Map Operation Test - generates test data for map pipeline

streams:
  input_target:
    topic: test-input-branch
    keyType: avro:SimpleKey
    valueType: avro:SimpleValue

producers:
  map_data_producer:
    to: input_target
    interval: 2s
    generator:
      globalCode: |
        global mapCounter
        mapCounter = 0
      code: |
        global mapCounter
        mapCounter += 1

        current = mapCounter

        key = None
        if current % 10 != 0:
          key = dict()
          key["count"] = current

        value = None
        if current % 10 != 1:
          value = dict()
          value["text"] = f"Test data to branch - {current}"
          value["count"] = current

      expression: (key,value)
      resultType: (avro:SimpleKey,avro:SimpleValue)
