# $schema: https://raw.githubusercontent.com/Axual/ksml/refs/tags/1.0.8/docs/ksml-language-spec.json

# join Operation Test - generates test data for join pipeline

streams:
  input_target:
    topic: test-input-join
    keyType: avro:SimpleKey
    valueType: avro:SimpleValue

producers:
  join_data_producer:
    to: input_target
    interval: 2s
    generator:
      globalCode: |
        global joinCounter
        joinCounter = 0
      code: |
        global joinCounter
        joinCounter += 1

        current = joinCounter

        key = None
        if current % 10 != 0:
          key = dict()
          key["count"] = current

        value = None
        if current % 10 != 1:
          value = dict()
          value["text"] = f"join test data - {current}"
          value["count"] = current

      expression: (key,value)
      resultType: (avro:SimpleKey,avro:SimpleValue)
