# $schema: https://raw.githubusercontent.com/Axual/ksml/refs/tags/1.0.8/docs/ksml-language-spec.json

# leftJoin Operation Test - generates test data for leftJoin pipeline

streams:
  input_target:
    topic: test-input-leftJoin
    keyType: avro:SimpleKey
    valueType: avro:SimpleValue

producers:
  leftJoin_data_producer:
    to: input_target
    interval: 2s
    generator:
      globalCode: |
        global leftJoinCounter
        leftJoinCounter = 0
      code: |
        global leftJoinCounter
        leftJoinCounter += 1

        current = leftJoinCounter

        key = None
        if current % 10 != 0:
          key = dict()
          key["count"] = current

        value = None
        if current % 10 != 1:
          value = dict()
          value["text"] = f"leftJoin test data - {current}"
          value["count"] = current

      expression: (key,value)
      resultType: (avro:SimpleKey,avro:SimpleValue)
