include:
  - ../../test-compose.yml
# Run all services to get Red Panda
services:
  # Create test data
  prepare_cluster:
    image: apache/kafka:4.0.0
    hostname: kafka-setup
    depends_on:
      broker:
        condition: service_healthy
        restart: false
    restart: on-failure
    command: "bash -c 'echo Trying to create topics... && \
                         /opt/kafka/bin/kafka-topics.sh --create --if-not-exists --bootstrap-server broker:9093 --partitions 1 --replication-factor 1 --topic axual-testing-compat-test-aggregate-stream-input && \
                         /opt/kafka/bin/kafka-topics.sh --create --if-not-exists --bootstrap-server broker:9093 --partitions 1 --replication-factor 1 --topic axual-testing-compat-test-aggregate-stream-output-aggregated && \
                         /opt/kafka/bin/kafka-topics.sh --create --if-not-exists --bootstrap-server broker:9093 --partitions 1 --replication-factor 1 --topic axual-testing-compat-io.ksml.compat-testing-definition-D10-stream_aggregate-changelog --config cleanup.policy=compact && \
                         /opt/kafka/bin/kafka-topics.sh --create --if-not-exists --bootstrap-server broker:9093 --partitions 1 --replication-factor 1 --topic axual-testing-compat-io.ksml.compat-testing-definition-D10-KSTREAM-AGGREGATE-STATE-STORE-0000000001-changelog --config cleanup.policy=compact && \
                         echo Done'"
