# $schema: https://raw.githubusercontent.com/Axual/ksml/refs/tags/1.0.8/docs/ksml-language-spec.json

# Filter Operation Test - generates test data for filter pipeline

streams:
  input_target:
    topic: test-input-filter
    keyType: avro:SimpleKey
    valueType: avro:SimpleValue

producers:
  filter_data_producer:
    to: input_target
    interval: 2s
    generator:
      globalCode: |
        global filterCounter
        filterCounter = 0
      code: |
        global filterCounter
        filterCounter += 1

        current = filterCounter

        key = None
        if current % 10 != 0:
          key = dict()
          key["count"] = current

        value = None
        if current % 10 != 1:
          value = dict()
          value["text"] = f"Test data to filter - {current}"
          value["count"] = current

      expression: (key,value)
      resultType: (avro:SimpleKey,avro:SimpleValue)
