# $schema: https://raw.githubusercontent.com/Axual/ksml/refs/tags/1.0.8/docs/ksml-language-spec.json

# Filter Operation Test - filters messages based on count field value

streams:
  input_stream:
    topic: test-count-stream-input
    keyType: avro:SimpleKey
    valueType: avro:SimpleValue
    offsetResetPolicy: earliest

  output_stream:
    topic: test-count-stream-output
    keyType: avro:SimpleKey
    valueType: long

pipelines:
  grouping_pipeline:
    from: input_stream
    via:
      - type: groupByKey
      - type: count
        name: stream_counter
        store:
          name: stream_count
          type: keyValue
          persistent: false
          timestamped: false
          keyType: avro:SimpleKey
          valueType: long
          caching: false
          logging: true
      - type: toStream
    to: output_stream


  inspect:
    from: output_stream
    forEach:
      code: |
        log.info("COUNT STREAM PIPELINE - Output message: key={}, value={}", key, value)
