# $schema: https://raw.githubusercontent.com/Axual/ksml/refs/tags/1.0.8/docs/ksml-language-spec.json

# Transform Operation Test - generates test data for transform pipeline

streams:
  input_target:
    topic: test-input-transform
    keyType: avro:SimpleKey
    valueType: avro:SimpleValue

producers:
  transform_data_producer:
    to: input_target
    interval: 2s
    generator:
      globalCode: |
        global transformCounter
        transformCounter = 0
      code: |
        global transformCounter
        transformCounter += 1

        current = transformCounter

        key = None
        if current % 10 != 0:
          key = dict()
          key["count"] = current

        value = None
        if current % 10 != 1:
          value = dict()
          value["text"] = f"Test data to transform - {current}"
          value["count"] = current

      expression: (key,value)
      resultType: (avro:SimpleKey,avro:SimpleValue)
