# $schema: https://raw.githubusercontent.com/Axual/ksml/refs/tags/1.0.8/docs/ksml-language-spec.json

# Copy Operation Test - generates test data for copy pipeline

streams:
  input_target:
    topic: test-input-avro-complex
    keyType: avro:SimpleKey
    valueType: avro:AggregatedSimpleValues

producers:
  copy_data_producer:
    to: input_target
    interval: 2s
    generator:
      globalCode: |
        global copyCounter
        copyCounter = 0
      code: |
        global copyCounter
        copyCounter += 1

        current = copyCounter

        key = None
        if current % 10 != 0:
          key = dict()
          key["count"] = current

        value = None
        if current % 10 != 1:
          value = dict()
          value["createdAt"] = f"Now for loop - {current}"
          value["aggregated"] = {}
          for repeated in range(current%5):
            repeatedObj = dict()
            repeatedObj["text"] = f"Loop {current} - repeat {repeated}"
            repeatedObj["count"] = repeated
            value["aggregated"][f"agg{repeated}"] = repeatedObj

      expression: (key,value)
      resultType: (avro:SimpleKey,avro:AggregatedSimpleValues)
