include:
  - ../../test-compose.yml
# Run all services to get Red Panda
services:

  # Create test data
  prepare_cluster:
    image: apache/kafka:4.0.0
    hostname: kafka-setup
    depends_on:
      broker:
        condition: service_healthy
        restart: false
    restart: on-failure
    command: "bash -c 'echo Trying to create topics... && \
                         /opt/kafka/bin/kafka-topics.sh --create --if-not-exists --bootstrap-server broker:9093 --partitions 1 --replication-factor 1 --topic axual-testing-compat-test-input-copy && \
                         /opt/kafka/bin/kafka-topics.sh --create --if-not-exists --bootstrap-server broker:9093 --partitions 1 --replication-factor 1 --topic axual-testing-compat-test-output-copy && \
                         echo Done'"

  ksml_v1_1:
    #    image: axual/ksml:local
    #    pull_policy: missing
    image: axual/ksml:snapshot
    pull_policy: always
    hostname: ksml-test
    restart: no
    ports:
      - 8088:8088
      - 9988:9988
    # Using this non-standard directory to verify nothing is hardcoded to the image default /ksml
    volumes:
      - ./runner/:/otherKsml/runner
      - ./config/:/otherKsml/config
      - ./schemas/:/otherKsml/schemas
    working_dir: /ksml
    command:
      - /otherKsml/runner/ksml-runner-full.yaml
    depends_on:
      broker:
        condition: service_healthy
        restart: false
      schema_registry:
        condition: service_healthy
        restart: false
      prepare_cluster:
        condition: service_completed_successfully
        restart: false

