# $schema: https://raw.githubusercontent.com/Axual/ksml/refs/tags/1.0.8/docs/ksml-language-spec.json

# reduce Operation Test - generates test data for reduce pipeline

streams:
  input_target:
    topic: test-input-reduce
    keyType: avro:SimpleKey
    valueType: avro:SimpleValue

producers:
  reduce_data_producer:
    to: input_target
    interval: 2s
    generator:
      globalCode: |
        global reduceCounter
        reduceCounter = 0
      code: |
        global reduceCounter
        reduceCounter += 1

        current = reduceCounter

        key = None
        if current % 10 != 0:
          key = dict()
          key["count"] = current

        value = None
        if current % 10 != 1:
          value = dict()
          value["text"] = f"reduce test data - {current}"
          value["count"] = current

      expression: (key,value)
      resultType: (avro:SimpleKey,avro:SimpleValue)
