include:
  - ../test-compose.yml
services:
  ksml_v1_0:
    image: axual/ksml:1.0.6
    pull_policy: missing
    hostname: ksml-test
    restart: no
    ports:
      - 8088:8088
      - 9988:9988
    # Using this non-standard directory to verify nothing is hardcoded to the image default /ksml
    volumes:
      - ./runner/:/otherKsml/runner
      - ./config/:/otherKsml/config
      - ./schemas/:/otherKsml/schemas
    working_dir: /ksml
    command:
      - /otherKsml/runner/ksml-runner-full.yaml
    depends_on:
      broker:
        condition: service_healthy
      schema_registry:
        condition: service_healthy
      prepare_cluster:
        condition: service_completed_successfully
        restart: false

